services:
  backend:
    build: .
    image: djangocontainerdemo_backend
    ports:
      - '8000-8004:8000'
    restart: unless-stopped      
    volumes:
      - .:/app:rw
    # depends_on:
    #   - db

  # db:
  #   image: mysql:8.3 # Specify the desired MySQL version
  #   environment:
  #     MYSQL_ROOT_PASSWORD: mypassword
  #     MYSQL_DATABASE: mydatabase
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   ports:
  #     - '3307:3306'
volumes:
  db_data:
