services:
  backend: &backend
    build: .
    image: djangocontainerdemo_backend
    ports:
      - '8000-8004:8000'
    restart: unless-stopped

  backend_local:
    <<: *backend
    volumes:
      - .:/app:rw
    profiles:
      - local
    # depends_on:
    #   - db

  backend_staging:
    <<: *backend
    profiles:
      - staging
    # depends_on:
    #   - db

  # db:
  #   image: mysql:8.3 # Specify the desired MySQL version
  #   environment:
  #     MYSQL_ROOT_PASSWORD: mypassword
  #     MYSQL_DATABASE: mydatabase
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   ports:
  #     - '3307:3306'
volumes:
  db_data:
